// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnreeidjpjzcbnwmumlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducmVlaWRqcGp6Y2Jud211bWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MjM3MDIsImV4cCI6MjA3NjM5OTcwMn0.ZDNvTs0UY3SzRhjJ8gWJ62fHu_jO7wt_apCc2-yMh68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});